server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # ==========================================
        # EVENT SERVICE
        # ==========================================

        - id: event-service-private
          uri: lb://event-service
          predicates:
            - Path=/users/*/events,/users/*/events/*

        - id: event-service-public
          uri: lb://event-service
          predicates:
            - Path=/events/**

        - id: event-service-api
          uri: lb://event-service
          predicates:
            - Path=/api/events/**,/api/events/short

        - id: event-service-admin
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**

        - id: event-service-location
          uri: lb://event-service
          predicates:
            - Path=/admin/locations/**

        - id: event-service-categories
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**,/categories/**

        # ==========================================
        # REQUEST SERVICE
        # ==========================================
        - id: request-service-private
          uri: lb://request-service
          predicates:
            - Path=/users/*/events/*/requests

        - id: request-service-api
          uri: lb://request-service
          predicates:
            - Path=/api/requests/**,/api/requests/confirmedByEventIds

        - id: request-service-public
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests,/users/*/requests/*/cancel
        # ==========================================
        # MAIN SERVICE
        # ==========================================

        - id: main-service-read
          uri: lb://main-service
          predicates:
            - Path=/compilations/**,/users/**,/admin/**
            - Method=GET
          filters:
            - name: Retry
              args:
                retries: 2
                statuses:
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms

        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/compilations/**,/users/**,/admin/**,/api/**


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    reactor.netty.http.server: DEBUG