server:
  port: 0

spring:
  application:
    name: main-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ewm_main_db
    username: postgres
    password: 54321
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true

  jpa:
    datasource-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
stats-server:
  id: stats-server

#eureka:
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#  cloud:
#    gateway:
#      routes:
#        -id: stats-route
#        uri: lb://stats-service
#        predicates:
#          - Path=/stats/**
