server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8
      force: true # Принудительно применять кодировку для запросов и ответов
      enabled: true

spring:
  application:
    name: main-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm_main_db
    username: postgres
    password: 54321
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true

  jpa:
    datasource-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
    circuitbreaker:
      configs:
        default:
          sliding-window-size: 5
          failure-rate-threshold: 50
          wait-duration-in-open-state: 10s
          permitted-number-of-calls-in-half-open-state: 3
    timelimiter:
      configs:
        default:
          timeout-duration: 3s
stats-server:
  id: stats-server
