server:
  port: 0

spring:
  application:
    name: analyzer
  datasource:
    url: jdbc:postgresql://localhost:5432/recommendation_db
    username: postgres
    password: 54321
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true

  jpa:
    datasource-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

grpc:
  server:
    port: 0

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.cloud.config: DEBUG
    com.zaxxer.hikari: DEBUG